#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase0
cleanFaMesh

rm -rf ./constant/Hidrograms
rm -rf ./constant/N_A_dict

rm -rf ./Results
rm -rf ./Images
rm -rf wedge*
#------------------------------------------------------------------------------
