#!/bin/sh
#SBATCH -J wedge_Par_reconstruct
#SBATCH -p slims
#SBATCH -n 4
#SBATCH --mem-per-cpu=2400
#SBATCH --mail-user=
#SBATCH --mail-type=ALL
#SBATCH --output=wedge_Par_reconstruct%j.out
#SBATCH --error=wedge_Par_reconstruct%j.err

srun -n 4 python3 Par_reconstructPar.py -h_flag -Cv_flag -Us_flag -Q_flag -deltaz0_flag
